{
  "openapi": "3.0.0",
  "info": {
    "title": "WhatsApp API",
    "description": "Basic Whatsapp API",
    "version": "1.0.0",
    "contact": {
      "name": "API Support",
      "url": "https://github.com/SheldonBakker/whatsapp-api/issues"
    }
  },
  "servers": [],
  "tags": [
    {
      "name": "Health",
      "description": "Health check endpoints to verify API status"
    },
    {
      "name": "Session",
      "description": "Manage WhatsApp Web sessions"
    },
    {
      "name": "Client",
      "description": "Core WhatsApp client operations"
    },
    {
      "name": "Message",
      "description": "Operations related to WhatsApp messages"
    }
  ],
  "paths": {
    "/ping": {
      "get": {
        "tags": [
          "Health"
        ],
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/session/start/{sessionId}": {
      "get": {
        "tags": [
          "Session"
        ],
        "summary": "Start new session",
        "description": "Starts a session for the given session ID.",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "Status of the initiated session.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StartSessionResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server Failure.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/session/status/{sessionId}": {
      "get": {
        "tags": [
          "Session"
        ],
        "summary": "Get session status",
        "description": "Status of the session with the given session ID.",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "Status of the session.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StatusSessionResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server Failure.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/session/qr/{sessionId}": {
      "get": {
        "tags": [
          "Session"
        ],
        "summary": "Get session QR code",
        "description": "QR code of the session with the given session ID.",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server Failure.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/session/qr/{sessionId}/image": {
      "get": {
        "tags": [
          "Session"
        ],
        "summary": "Get session QR code as image",
        "description": "QR code as image of the session with the given session ID.",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "QR image.",
            "content": {
              "image/png": {}
            }
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server Failure.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/session/restart/{sessionId}": {
      "get": {
        "tags": [
          "Session"
        ],
        "summary": "Restart session",
        "description": "Restarts the session with the given session ID.",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "Sessions restarted.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RestartSessionResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server Failure.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/session/terminate/{sessionId}": {
      "get": {
        "tags": [
          "Session"
        ],
        "summary": "Terminate session",
        "description": "Terminates the session with the given session ID.",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "Sessions terminated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TerminateSessionResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server Failure.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/session/terminateInactive": {
      "get": {
        "tags": [
          "Session"
        ],
        "summary": "Terminate inactive sessions",
        "description": "Terminates all inactive sessions.",
        "responses": {
          "200": {
            "description": "Sessions terminated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TerminateSessionsResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server Failure.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/session/terminateAll": {
      "get": {
        "tags": [
          "Session"
        ],
        "summary": "Terminate all sessions",
        "description": "Terminates all sessions.",
        "responses": {
          "200": {
            "description": "Sessions terminated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TerminateSessionsResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server Failure.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/client/getClassInfo/{sessionId}": {
      "get": {
        "tags": [
          "Client"
        ],
        "description": "",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotFoundResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/client/getNumberId/{sessionId}": {
      "post": {
        "tags": [
          "Client"
        ],
        "description": "",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotFoundResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "number": {
                    "type": "string",
                    "description": "The number or ID ('@c.us' will be automatically appended if not specified)",
                    "example": "6281288888888"
                  }
                }
              }
            },
            "application/xml": {
              "schema": {
                "type": "object",
                "properties": {
                  "number": {
                    "type": "string",
                    "description": "The number or ID ('@c.us' will be automatically appended if not specified)",
                    "example": "6281288888888"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/client/getState/{sessionId}": {
      "get": {
        "tags": [
          "Client"
        ],
        "description": "",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/client/sendMessage/{sessionId}": {
      "post": {
        "tags": [
          "Client"
        ],
        "description": "",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotFoundResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "chatId": {
                    "type": "string",
                    "description": "The Chat id which contains the message (Group or Individual)"
                  },
                  "contentType": {
                    "type": "string",
                    "description": "The type of message content, must be one of the following: string, MessageMedia, MessageMediaFromURL, Location, Buttons, or List"
                  },
                  "content": {
                    "type": "object",
                    "description": "The content of the message, can be a string or an object"
                  },
                  "options": {
                    "type": "object",
                    "description": "The message send options"
                  }
                }
              },
              "examples": {
                "string": {
                  "value": {
                    "chatId": "6281288888888@c.us",
                    "contentType": "string",
                    "content": "Hello World!"
                  }
                },
                "MessageMedia": {
                  "value": {
                    "chatId": "6281288888888@c.us",
                    "contentType": "MessageMedia",
                    "content": {
                      "mimetype": "image/jpeg",
                      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
                      "filename": "image.jpg"
                    }
                  }
                },
                "MessageMediaFromURL": {
                  "value": {
                    "chatId": "6281288888888@c.us",
                    "contentType": "MessageMediaFromURL",
                    "content": "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=Example"
                  }
                },
                "Location": {
                  "value": {
                    "chatId": "6281288888888@c.us",
                    "contentType": "Location",
                    "content": {
                      "latitude": -6.2,
                      "longitude": 106.8,
                      "description": "Jakarta"
                    }
                  }
                },
                "Buttons": {
                  "value": {
                    "chatId": "6281288888888@c.us",
                    "contentType": "Buttons",
                    "content": {
                      "body": "Hello World!",
                      "buttons": [
                        {
                          "body": "button 1"
                        }
                      ],
                      "title": "Hello World!",
                      "footer": "Hello World!"
                    }
                  }
                },
                "List": {
                  "value": {
                    "chatId": "6281288888888@c.us",
                    "contentType": "List",
                    "content": {
                      "body": "Hello World!",
                      "buttonText": "Hello World!",
                      "sections": [
                        {
                          "title": "sectionTitle",
                          "rows": [
                            {
                              "id": "customId",
                              "title": "ListItem2",
                              "description": "desc"
                            },
                            {
                              "title": "ListItem2"
                            }
                          ]
                        }
                      ],
                      "title": "Hello World!",
                      "footer": "Hello World!"
                    }
                  }
                },
                "Contact": {
                  "value": {
                    "chatId": "6281288888888@c.us",
                    "contentType": "Contact",
                    "content": {
                      "contactId": "6281288888889@c.us"
                    }
                  }
                },
                "Poll": {
                  "value": {
                    "chatId": "6281288888888@c.us",
                    "contentType": "Poll",
                    "content": {
                      "pollName": "Cats or Dogs?",
                      "pollOptions": [
                        "Cats",
                        "Dogs"
                      ],
                      "options": {
                        "allowMultipleAnswers": true
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/client/getWWebVersion/{sessionId}": {
      "get": {
        "tags": [
          "Client"
        ],
        "description": "",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotFoundResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ]
      }
    },
    "/message/delete/{sessionId}": {
      "post": {
        "tags": [
          "Message"
        ],
        "description": "",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Unique identifier for the session (alphanumeric and - allowed)",
            "example": "f8377d8d-a589-4242-9ba6-9486a04ef80c"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Forbidden.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ForbiddenResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotFoundResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "apiKeyAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "chatId": {
                    "type": "string",
                    "description": "The Chat id which contains the message",
                    "example": "6281288888888@c.us"
                  },
                  "messageId": {
                    "type": "string",
                    "description": "Unique whatsApp identifier for the message",
                    "example": "ABCDEF999999999"
                  }
                }
              }
            },
            "application/xml": {
              "schema": {
                "type": "object",
                "properties": {
                  "chatId": {
                    "type": "string",
                    "description": "The Chat id which contains the message",
                    "example": "6281288888888@c.us"
                  },
                  "messageId": {
                    "type": "string",
                    "description": "Unique whatsApp identifier for the message",
                    "example": "ABCDEF999999999"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "StartSessionResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "Session initiated successfully"
          }
        },
        "xml": {
          "name": "StartSessionResponse"
        }
      },
      "StatusSessionResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "state": {
            "type": "string",
            "example": "CONNECTED"
          },
          "message": {
            "type": "string",
            "example": "session_connected"
          }
        },
        "xml": {
          "name": "StatusSessionResponse"
        }
      },
      "RestartSessionResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "Restarted successfully"
          }
        },
        "xml": {
          "name": "RestartSessionResponse"
        }
      },
      "TerminateSessionResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "Logged out successfully"
          }
        },
        "xml": {
          "name": "TerminateSessionResponse"
        }
      },
      "TerminateSessionsResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "Flush completed successfully"
          }
        },
        "xml": {
          "name": "TerminateSessionsResponse"
        }
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "error": {
            "type": "string",
            "example": "Error message"
          }
        },
        "xml": {
          "name": "ErrorResponse"
        }
      },
      "NotFoundResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "error": {
            "type": "string",
            "example": "Resource not found"
          }
        },
        "xml": {
          "name": "NotFoundResponse"
        }
      },
      "ForbiddenResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "error": {
            "type": "string",
            "example": "Invalid API key"
          }
        },
        "xml": {
          "name": "ForbiddenResponse"
        }
      }
    },
    "securitySchemes": {
      "apiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key"
      }
    }
  },
  "security": [
    {
      "apiKeyAuth": []
    }
  ]
}